const fs = require("fs");
const path = require("path");

function getAllDtsFiles(dir, fileList = []) {
    const files = fs.readdirSync(dir);

    for (const file of files) {
        if (file === "node_modules") continue;
        if (file === "dist") continue;
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat.isDirectory()) {
            getAllDtsFiles(filePath, fileList);
        } else if (file.endsWith(".d.ts")) {
            fileList.push(filePath);
        }
    }

    return fileList;
}

function generateIndexDts() {
    const renderUtilsPath = __dirname;
    const dtsFiles = getAllDtsFiles(renderUtilsPath);

    const excludedModules = ["socket-function/index"];

    const modules = dtsFiles
        .map(filePath => {
            const relativePath = path.relative(renderUtilsPath, filePath);
            const withoutExt = relativePath.replace(/\.d\.ts$/, "");
            const modulePath = "socket-function/" + withoutExt.replace(/\\/g, "/");
            if (excludedModules.includes(modulePath)) return undefined;

            let content = fs.readFileSync(filePath, "utf8");

            // Resolve relative imports to absolute module paths
            const moduleDir = path.dirname(modulePath);
            content = content.replace(
                /(import|export)\s+([^"']*)\s+from\s+["'](\.[^"']+)["']/g,
                (match, keyword, imported, relativeImport) => {
                    const absoluteModulePath = path.join(moduleDir, relativeImport).replace(/\\/g, "/");
                    return `${keyword} ${imported} from "${absoluteModulePath}"`;
                }
            );

            // Resolve dynamic imports like import("../path")
            content = content.replace(
                /import\(["'](\.[^"']+)["']\)/g,
                (match, relativeImport) => {
                    const absoluteModulePath = path.join(moduleDir, relativeImport).replace(/\\/g, "/");
                    return `import("${absoluteModulePath}")`;
                }
            );

            const indentedContent = content
                .split("\n")
                .map(line => line ? "    " + line : line)
                .join("\n");

            return `declare module "${modulePath}" {\n${indentedContent}\n}`;
        })
        .filter(x => x)
        .sort()
        .join("\n\n");

    const outputPath = path.join(__dirname, "index.d.ts");
    const header = `// Auto-generated file. Do not edit manually.\n// Generated by: yarn generate-index-dts\n\n`;

    fs.writeFileSync(outputPath, header + modules + "\n", "utf8");
    console.log(`Generated ${outputPath} with ${dtsFiles.length} module declarations`);
}

generateIndexDts();

